name: Cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12]

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: yarn install, generate
        run: |
          yarn install
          yarn gen-domain-set-test
      - name: commit, push
        uses: EndBug/add-and-commit@v5
        with:
          add: 'domain-set-test'
          author_name: test
          author_email: test
          message: 'auto update'
        env:
          GITHUB_TOKEN: 7febfbdbf0ad4c87e162ffb7d4726cf37c1a8a89
